- hosts: 
  - centos7-host


  pre_tasks:
  - shell: echo 'Start'

  tasks:
  - name: Install the latest version of Java
    yum:    
      name: java
      state: latest
  #  become: yes
  #  become_user: root 

  post_tasks:
  - shell: echo 'Finish'