- name: ========== Java package copying ==========
  copy:
    src: java_sw/jdk-{{java_version}}-linux-x64.tar.gz
    dest: "{{path_to_download}}"

- name: ========== Java directory creating ==========
  file:
    path: "{{java_home}}jdk1.{{java_version}}"
    state: directory
    #mode: 0755

- name: ========== Java package unarchiving ==========
  unarchive:
    src: "{{path_to_download}}jdk-{{java_version}}-linux-x64.tar.gz"
    dest: "{{java_home}}jdk1.{{java_version}}"
    extra_opts: "--strip-components=1"
    remote_src: yes
    #list_files: yes
  become: yes

- name: XXX
  shell: echo "Centosik"
  when: ansible_os_family == 'RedHa'

- name: correct java version selected
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{java_home}}jdk1.{{java_version}}/bin/java"





    #--no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" 
#http://download.oracle.com/otn/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz